kind: pipeline
type: docker
name: default

steps:
- name: unittest
  image: python:3.10-slim-buster
  commands:
    - pip install -r requirements.txt
    - pip install pytest
    - py.test
- name: docker-publish
  image: plugins/docker
  when:
    event: [ push ]
  settings:
    repo: quay.io/dotmesh/sklearn-flask
    registry: quay.io
    dockerfile: Dockerfile
    tags:
      - ${DRONE_COMMIT_SHA}
      - ${DRONE_BRANCH}
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password

- name: docker-publish-tag
  image: plugins/docker
  settings:
    auto_tag: true
    registry: quay.io
    repo: quay.io/dotmesh/sklearn-flask        
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password

- name: slack
  image: plugins/slack
  when:
    event: [ push ]
    status: [ success, failure ]
  depends_on:
  - docker-publish
  settings:
    webhook:
      from_secret: slack_url
    channel: ci
    username: drone
    icon_url: https://i.pinimg.com/originals/51/29/a4/5129a48ddad9e8408d2757dd10eb836f.jpg
- name: slack-tag
  image: plugins/slack
  when:
    event: [ tag ]
    status: [ success, failure ]
  depends_on:
  - docker-publish-tag
  settings:
    webhook:
      from_secret: slack_url
    channel: ci
    username: drone
    icon_url: https://i.pinimg.com/originals/51/29/a4/5129a48ddad9e8408d2757dd10eb836f.jpg
