FROM quay.io/dotmesh/sklearn-flask:1.2.1-python3.7
ARG model_name
# Set where models should be stored in the container
ENV MODEL_BASE_PATH=/models
RUN mkdir -p ${MODEL_BASE_PATH}

ENV MODEL_NAME=$model_name
ENV MODEL_JOBLIB_FILE=${MODEL_BASE_PATH}/${MODEL_NAME}
# Copying the model
COPY ./${MODEL_NAME} ${MODEL_BASE_PATH}/${MODEL_NAME}