FROM quay.io/dotmesh/sklearn-flask:dev
ARG model_name
# Set where models should be stored in the container
ENV MODEL_BASE_PATH=/models
RUN mkdir -p ${MODEL_BASE_PATH}

ENV MODEL_NAME=$model_name
ENV MODEL_JOBLIB_FILE=${MODEL_BASE_PATH}/${MODEL_NAME}
# Copying the model; it might be a tarball of files:
COPY ./${MODEL_NAME} ${MODEL_BASE_PATH}/${MODEL_NAME}
